[[nav]]
page = "index"

[[nav]]
separator = "Guides"

[[nav]]
autodiscover = "guides"

[[nav]]
separator = true

[[nav]]
separator = "Writing Content"

[[nav]]
autodiscover = "writing"

[[nav]]
separator = "Reference"

[[nav]]
autodiscover = "reference"

[[nav]]
label = "Development"
autodiscover = "development"